-- ============================================================================
-- AUTO EXPIRED LABEL SISTEM (AELS) - SUPABASE DATABASE CONFIGURATION
-- ============================================================================
-- Petunjuk Penggunaan:
-- 1. Buka Dashboard Supabase Anda (https://supabase.com).
-- 2. Pilih Proyek Anda.
-- 3. Di menu sebelah kiri, klik "SQL Editor".
-- 4. Klik "New query".
-- 5. Salin dan tempel (copy-paste) seluruh isi script SQL di bawah ini.
-- 6. Klik tombol "Run" di kanan bawah.
-- ============================================================================

-- 1. Membuat Tabel Master SOP Produk
CREATE TABLE IF NOT EXISTS aels_master_products (
    id text primary key,
    name text not null,
    category text not null,
    days integer not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Membuat Tabel Riwayat Pelabelan (History Cetak)
CREATE TABLE IF NOT EXISTS aels_products (
    id text primary key,
    name text not null,
    category text not null,
    open_date text not null,
    shelf_life integer not null,
    expiry_date text not null,
    notes text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Membuat Tabel Daftar Barista
CREATE TABLE IF NOT EXISTS aels_baristas (
    id bigint generated by default as identity primary key,
    name text unique not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Membuat Tabel Pengaturan Printer & Counter
CREATE TABLE IF NOT EXISTS aels_print_settings (
    id integer primary key,
    printer_type text not null,
    printer_ip_address text,
    printer_port text default '9100',
    label_size text not null,
    total_printed integer not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Mengaktifkan Replikasi Realtime Supabase (Postgres Changes)
-- Agar perubahan data di satu tab/perangkat langsung tersinkron secara real-time ke tab/perangkat lainnya.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
        -- Tambahkan tabel aels_master_products ke publikasi realtime jika belum ada
        IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'aels_master_products') THEN
            ALTER PUBLICATION supabase_realtime ADD TABLE aels_master_products;
        END IF;
        
        -- Tambahkan tabel aels_products ke publikasi realtime jika belum ada
        IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'aels_products') THEN
            ALTER PUBLICATION supabase_realtime ADD TABLE aels_products;
        END IF;
        
        -- Tambahkan tabel aels_baristas ke publikasi realtime jika belum ada
        IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'aels_baristas') THEN
            ALTER PUBLICATION supabase_realtime ADD TABLE aels_baristas;
        END IF;
        
        -- Tambahkan tabel aels_print_settings ke publikasi realtime jika belum ada
        IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'aels_print_settings') THEN
            ALTER PUBLICATION supabase_realtime ADD TABLE aels_print_settings;
        END IF;
    END IF;
END $$;

-- 6. Menonaktifkan Row Level Security (RLS) pada semua tabel
-- Karena aplikasi AELS bertipe local/internal client-only tanpa authentication,
-- RLS dinonaktifkan agar client dapat langsung melakukan read/write via anon key.
ALTER TABLE aels_master_products DISABLE ROW LEVEL SECURITY;
ALTER TABLE aels_products DISABLE ROW LEVEL SECURITY;
ALTER TABLE aels_baristas DISABLE ROW LEVEL SECURITY;
ALTER TABLE aels_print_settings DISABLE ROW LEVEL SECURITY;
